<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sflow-pseudo-checkbox_Liste des tches_sflow_a3d9ad (1)</name>
   <tag></tag>
   <elementGuidId>65782992-5a7c-4efc-bdd9-6347f6dd102d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>sflow-pseudo-checkbox.sflow-pseudo-checkbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//sflow-pseudo-checkbox[@type='todo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>sflow-pseudo-checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sflow-pseudo-checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sflog</name>
      <type>Main</type>
      <value>milestone_checked</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>todo</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;with-chatbox-support-icon&quot;]/app-root[@class=&quot;ng-tns-c285-0&quot;]/div[@class=&quot;desktop__wrapper ng-tns-c285-0 ng-trigger ng-trigger-routeAnimations&quot;]/app-startupflow-shell[@class=&quot;hidden_toolbar ng-star-inserted&quot;]/div[@class=&quot;shell__wrapper&quot;]/div[@class=&quot;main&quot;]/provider-layout[@class=&quot;ng-tns-c657-39 ng-star-inserted&quot;]/provider-content[@class=&quot;ng-tns-c657-39&quot;]/div[@class=&quot;inno-provider-wrapper&quot;]/provider-status[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;main-container ng-star-inserted&quot;]/sflow-workflow[@class=&quot;ng-star-inserted&quot;]/sflow-card[@class=&quot;workflow__card-wrapper ng-star-inserted&quot;]/sflow-accordion[1]/div[@class=&quot;accordion-content&quot;]/sflow-accordion-content[@class=&quot;ng-star-inserted&quot;]/sflow-workflow-contents[1]/div[@class=&quot;workflow__milestone-block ng-star-inserted&quot;]/sflow-workflow-milestones-list[1]/div[@class=&quot;sflow-item__wrapper ng-star-inserted&quot;]/ul[@class=&quot;milestone-list&quot;]/sflow-milestone-item[@class=&quot;ng-star-inserted&quot;]/li[@class=&quot;milestone-item ng-star-inserted&quot;]/sflow-pseudo-checkbox[@class=&quot;sflow-pseudo-checkbox&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//sflow-pseudo-checkbox[@type='todo']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//sflow-pseudo-checkbox</value>
   </webElementXpaths>
</WebElementEntity>
